name: macos-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  appleclang-minimum:
    name: appleclang-10.0.1
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_10.3.app/Contents/Developer

    steps:
    - uses: actions/checkout@v2
    - name: submodules
      run: git submodule update --init --recursive
    - name: dependencies
      run: brew install boost cryptopp
    - name: cmake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug
    - name: build
      run: cmake --build build
    - name: test
      run: ./build/tests/tests

  appleclang-latest:
    name: appleclang-11.0.3
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: submodules
      run: git submodule update --init --recursive
    - name: dependencies
      run: brew install boost cryptopp
    - name: cmake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug
    - name: build
      run: cmake --build build
    - name: test
      run: ./build/tests/tests
