name: ubuntu-latest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  clang:
    name: clang++-6
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: submodules
      run: git submodule update --init --recursive
    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsodium-dev libcrypto++-dev libboost-all-dev
    - name: cmake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=clang++-6.0
    - name: build
      run: cmake --build build -j$(nproc)
    - name: test
      run: ./build/tests/tests

  gcc:
    name: g++-8
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: submodules
      run: git submodule update --init --recursive
    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsodium-dev libcrypto++-dev libboost-all-dev
    - name: cmake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_COMPILER=g++-8
    - name: build
      run: cmake --build build -j$(nproc)
    - name: test
      run: ./build/tests/tests
